// src/vue/AIDatepicker.vue
<script setup>
import { ref } from 'vue';
import {fetchDate, tryCatch} from "../core";

const props = defineProps({
  aidp: {
    type: String,
    default: 'default'
  },
  placeholder: {
    type: String,
    default: 'eg: Next Monday'
  },
  hint: {
    type: String,
    required: false
  },
  region: {
    type: String,
    required: false
  },
  format: {
    type: String,
    required: false
  }
});

const emit = defineEmits(['fetching', 'error', 'selected', 'done']);

const query = ref('');
const result = ref('');


const handleFetch = async () => {
  emit('fetching');

  const { data, error } = await tryCatch(fetchDate(query.value, props.hint, props.region, props.format));

  if (error) {
    emit('error', error);
  } else {
    result.value = data;
    emit('selected', data);
  }

  emit('done', error);
};
</script>

<template>
  <div>
    <input
        class="aidp-date"
        :placeholder="placeholder"
        v-model="query"
        @keydown.enter="handleFetch"
    />
    <button
        class="aidp-button"
        type="button"
        @click="handleFetch"
    >
      ✔
    </button>
    <div
        class="aidp-result">
      {{ result }}
    </div>
  </div>
</template>

<style scoped>
input {
  margin-right: 0.5rem;
}
</style>

// src/react/AIDatepicker.jsx
import { useState } from 'react';
import { fetchDate, tryCatch } from '../core';

export default function AIDatepicker({
                                         aidp = 'default',
                                         placeholder = 'eg: Next Monday',
                                         region,
                                         format,
                                         hint,
                                         onFetching,
                                         onSelected,
                                         onError,
                                         onDone
                                     }) {
    const [query, setQuery] = useState('');
    const [result, setResult] = useState('');

    const handleFetch = async () => {
        onFetching?.();

        const { data, error } = await tryCatch(
            fetchDate(query, hint, region, format) // 🧠 Pass hint
        );

        if (error) {
            onError?.(error);
        } else {
            setResult(data);
            onSelected?.(data);
        }

        onDone?.(error);
    };

    return (
        <div>
            <input
                class="aidp-date"
                placeholder={placeholder}
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleFetch()}
            />
            <button class="aidp-button"
                    type="button"
                    onClick={handleFetch}>
                ✔
            </button>
            <div  class="aidp-result">{result}</div>
        </div>
    );
}
